BAU: Handle null userProfile in error helper
The error below has been seen on production. We are performing an unsafe method call on the userProfile object at present which can lead to a NullPointerException. We should fall back to the default user identifier if userProfile is null.

Truncated error stack trace:

```
java.lang.NullPointerException: Cannot invoke "uk.gov.di.authentication.shared.entity.UserProfile.getSubjectID()" because "userProfile" is null
	at uk.gov.di.authentication.frontendapi.lambda.CheckReAuthUserHandler.generateErrorResponse(CheckReAuthUserHandler.java:208)
```